### ISSUE TITLE
Paparazzi record all snapshots again

### ISSUE THREAD

**Issue by M0hammed** [cashapp/paparazzi#1597]
**Description**

After updating Paparazzi from `v1.3.1 `to `v1.3.4` to address `OutOfMemory (OOM)` errors, a significant number of tests started failing, while using `maxPercentDifference: Double = 0.1`. Running the `./gradlew recordPaparazziDebug` command regenerated all snapshots, despite no changes in the codebase.

**Steps to Reproduce**

- Update Paparazzi to v1.3.4.
- Run ./gradlew verifyPaparazziDebug.
- Observe that many tests fail unexpectedly.
- Run ./gradlew recordPaparazziDebug.
- Notice that all snapshots are regenerated, even though no code changes were made.

**Expected Behavior**

- The tests should pass without regenerating snapshots unnecessarily. If there are no changes in the code, Paparazzi should load - snapshots from the cache instead of regenerating them.

**Additional Information**

Paparazzi Version: 1.3.4
OS: macOS
Compile SDK: 34
Gradle Version: 8.9
Android Gradle Plugin Version: 8.5.1

**Comment by geoff-powell** [comment]
Version 1.3.4 had some known changes in rendering which unfortunately would require some snapshot regen. @jrodbx was able to diagnose this change and fix [it ](https://github.com/cashapp/paparazzi/pull/1503). Once our next version is out, it should fix this issue. If you want to try the latest and greatest, try using the `1.3.5-SNAPSHOT` version.

**Comment by nicbell** [comment]
You do have to re-record snapshots if there are significant changes to `layoutlib`. Same as how previews sometimes look a bit different / better after upgrading Android Studio.

**Comment by jdeebee** [comment]
@geoff-powell This is still reproducible on 1.3.5. Are there any plans for a fix or new releases?

**Comment by geoff-powell** [comment]
@jdeebee Yes @nicbell is correct. Due the nature of layoutlib changes, it may result in new snapshots getting generated after a version bump. Sometimes these diffs are hard to see visually as they could be related to anti aliasing or text rendering changes.

The ultimate goal would be snapshots not changing when no code changes were made but this is not the reality of layoutlib's rendering.
